export default [
  { "from":  "/test/redirect", "to":  "/next/" },
  { "from":  "/get-started/sparsify-a-model", "to":  "/get-started/optimize" },

  // { "from":  "/user-guides/recipes", "to":  "/guides/recipes/" },
  // { "from":  "/user-guides/onnx-export", "to":  "/guides/onnx/export" },

  { "from":  "/sparseml/", "to":  "/products/sparseml/" },
  { "from":  "/sparsezoo/", "to":  "/products/sparsezoo/" },
  { "from":  "/sparsify/", "to":  "https://github.com/neuralmagic/sparsify" },
  { "from":  "/deepsparse/", "to":  "/products/deepsparse/" },
  { "from":  "/archive/sparseml/", "to":  "/products/sparseml/" },
  { "from":  "/archive/sparsezoo/", "to":  "/products/sparsezoo/" },
  { "from":  "/archive/deepsparse/", "to":  "/products/deepsparse/" },
  { "from": "/use-cases", "to": "/#tasks" },
  { "from": "/get-started/deploy-a-model", "to": "/get-started/deploy" },
  { "from": "/get-started/install/deepsparse-ent", "to": "/get-started/install/deepsparse#enterprise-installation" },
  { "from": "/get-started/sparsify-a-model/supported-integrations/", "to": "/get-started/optimize" },
  { "from": "/get-started/transfer-a-sparsified-model", "to": "/get-started/transfer" },
  { "from": "/get-started/use-a-model", "to": "/get-started/deploy" },
  { "from": "/index/deploy-workflow/", "to": "/get-started/deploy" },
  { "from": "/index/optimize-workflow/", "to": "/get-started/optimize" },
  { "from": "/index/quick-tour", "to": "/get-started/" },
  { "from": "/products/deepsparse/", "to": "/products/deepsparse/" },

  // { "from": "/products/deepsparse/cpp-api", "to": "/products/deepsparse/api-cpp/" },
  // { "from": "/products/deepsparse/python-api/", "to": "/products/deepsparse/api-python/" },
  // { "from": "/products/deepsparse/cli/", "to": "/products/deepsparse/cli/" },

  { "from": "/products/deepsparse/community/", "to": "/products/deepsparse/" },

  // { "from": "/products/deepsparse/community/cli/", "to": "/products/deepsparse/cli/" },
  // { "from": "/products/deepsparse/community/cpp-api", "to": "/products/deepsparse/api-cpp/" },
  // { "from": "/products/deepsparse/community/python-api/", "to": "/products/deepsparse/api-python/" },
  // { "from": "/products/deepsparse/enterprise/", "to": "/products/deepsparse/enterprise" },
  // { "from": "/products/deepsparse/enterprise/cli/", "to": "/products/deepsparse/cli/" },
  // { "from": "/products/deepsparse/enterprise/cpp-api", "to": "/products/deepsparse/api-cpp/" },
  // { "from": "/products/deepsparse/enterprise/python-api/", "to": "/products/deepsparse/api-python/" },

  { "from": "/products/sparseml/", "to": "/products/sparseml/" },
  // { "from": "/products/sparseml/python-api", "to": "/products/sparseml/api-python/" },
  // { "from": "/products/sparseml/cli", "to": "/products/sparseml/cli/" },
  { "from": "/sparsezoo/source/models", "to": "https://sparsezoo.neuralmagic.com" },
  { "from": "/sparsezoo/source/recipes", "to": "https://sparsezoo.neuralmagic.com" },
  // { "from": "/use-cases/deploying-deepsparse/docker", "to": "/guides/docker" },
  { "from": "/use-cases/embedding-extraction", "to": "https://github.com/neuralmagic/deepsparse/blob/main/integrations/haystack" },
  { "from": "/use-cases/image-classification", "to": "/computer-vision/image-classification/" },
  { "from": "/use-cases/image-classification/deploying", "to": "/computer-vision/image-classification/#deployment" },
  { "from": "/use-cases/image-classification/sparsifying", "to": "/computer-vision/image-classification/#optimizing" },
  { "from": "/use-cases/natural-language-processing", "to": "/nlp/" },
  { "from": "/use-cases/natural-language-processing/deploying", "to": "/nlp/#deployment" },
  { "from": "/use-cases/natural-language-processing/sparsifying", "to": "/nlp/#optimizing" },
  { "from": "/use-cases/natural-language-processing/text-classification", "to": "/nlp/" },
  { "from": "/use-cases/natural-language-processing/token-classification", "to": "/nlp/" },
  { "from": "/use-cases/natural-language-processing/sentiment-analysis", "to": "/nlp/" },
  { "from": "/use-cases/natural-language-processing/question-answering", "to": "/nlp/" },
  { "from": "/use-cases/object-detection", "to": "/computer-vision/object-detection/" },
  { "from": "/use-cases/object-detection/deploying", "to": "/computer-vision/object-detection/#deployment" },
  { "from": "/use-cases/object-detection/sparsifying", "to": "/computer-vision/object-detection/#optimizing" },

  // { "from": "/user-guides/deepsparse-engine", "to": "/guides/deepsparse/" },
  // { "from": "/user-guides/deepsparse-engine/", "to": "/guides/deepsparse/" },
  // { "from": "/user-guides/deepsparse-engine/benchmarking", "to": "/guides/deepsparse/benchmarking" },
  // { "from": "/user-guides/deepsparse-engine/benchmarking/", "to": "/guides/deepsparse/benchmarking" },
  // { "from": "/user-guides/deepsparse-engine/diagnostics-debugging", "to": "/guides/deepsparse/diagnostics-debugging" },
  // { "from": "/user-guides/deepsparse-engine/diagnostics-debugging/", "to": "/guides/deepsparse/diagnostics-debugging" },
  // { "from": "/user-guides/deepsparse-engine/hardware-support", "to": "/guides/deepsparse/hardware-support" },
  // { "from": "/user-guides/deepsparse-engine/hardware-support/", "to": "/guides/deepsparse/hardware-support" },
  // { "from": "/user-guides/deepsparse-engine/logging", "to": "/guides/deepsparse/logging" },
  // { "from": "/user-guides/deepsparse-engine/logging/", "to": "/guides/deepsparse/logging" },
  // { "from": "/user-guides/deepsparse-engine/numactl-utility", "to": "/guides/deepsparse/numactl-utility" },
  // { "from": "/user-guides/deepsparse-engine/numactl-utility/", "to": "/guides/deepsparse/numactl-utility" },
  // { "from": "/user-guides/deepsparse-engine/scheduler", "to": "/guides/deepsparse/scheduler" },
  // { "from": "/user-guides/deepsparse-engine/scheduler/", "to": "/guides/deepsparse/scheduler" },
  // { "from": "/user-guides/deploying-deepsparse", "to": "/guides/deploying-deepsparse/" },
  // { "from": "/user-guides/deploying-deepsparse/", "to": "/guides/deploying-deepsparse/" },
  // { "from": "/user-guides/deploying-deepsparse/amazon-sagemaker", "to": "/guides/deploying-deepsparse/amazon-sagemaker" },
  // { "from": "/user-guides/deploying-deepsparse/amazon-sagemaker/", "to": "/guides/deploying-deepsparse/amazon-sagemaker" },
  // { "from": "/user-guides/deploying-deepsparse/aws-lambda", "to": "/guides/deploying-deepsparse/aws-lambda" },
  // { "from": "/user-guides/deploying-deepsparse/aws-lambda/", "to": "/guides/deploying-deepsparse/aws-lambda" },
  // { "from": "/user-guides/deploying-deepsparse/deepsparse-server", "to": "/guides/deploying-deepsparse/deepsparse-server" },
  // { "from": "/user-guides/deploying-deepsparse/deepsparse-server/", "to": "/guides/deploying-deepsparse/deepsparse-server" },
  // { "from": "/user-guides/onn-export", "to": "/guides/onnx/export" },
  // { "from": "/user-guides/onn-export/", "to": "/guides/onnx/export" },
  // { "from": "/user-guides/recipes", "to": "/guides/recipes/" },
  // { "from": "/user-guides/recipes/", "to": "/guides/recipes/" },
  // { "from": "/user-guides/recipes/creating", "to": "/guides/recipes/" },
  // { "from": "/user-guides/recipes/creating/", "to": "/guides/recipes/" },
  // { "from": "/user-guides/recipes/enabling", "to": "/guides/recipes/" },
  // { "from": "/user-guides/recipes/enabling/", "to": "/guides/recipes/" },
  // { "from": "/user-guides/sparsification", "to": "/guides/sparsification/" },
]
