# config.yaml
endpoints:
    - task: embedding_extraction
      model: zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/pruned95_quant-none
      kwargs:
        base_task: image_classification
        emb_extraction_layer: -3
