loggers:
  custom_logger:
    path: example_custom_logger.py:CustomLogger
    # arg_1: your_arg_1

endpoints:
  - task: sentiment_analysis
    route: /sentiment_analysis/predict
    model: zoo:nlp/sentiment_analysis/bert-base/pytorch/huggingface/sst2/12layer_pruned80_quant-none-vnni
    name: sentiment_analysis_pipeline
    data_logging:
      pipeline_inputs:
        - func: identity
          frequency: 1
          target_loggers:
            - custom_logger