name: Build and Commit

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    if: github.event.commits[0].author.name != 'nm-automation'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CICD_GITHUB_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: make build

      - name: Git setup
        run: |
          git config user.name "nm-automation"
          git config user.email "actions@github.com"

      - name: Commit changes
        run: |
          make git_add
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated build"
          git push
