name: Nightly Redirects Checker

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: peter-evans/linkcheck@v1
        with:
          args: tests/test-redirects.txt
          reporter: 'github-actions'